### PR TITLE
reducing poll latency with ioctl serial control

### PR DESCRIPTION
**Pull request by catch-twenty-two**
This pr fixes the latency on the serial port that is only noticeable when communicating at high speeds.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Tested on HW.

**Comment by lucasdemarchi** [comment]
Tested on *which* hardware is the important part missing here. I suppose it's an ftdi converter?

Please add such details to the commit message.

**Comment by jkflying** [comment]
I tested this on FTDI on an Up Core board, and it noticeably reduced latency.

Also of interest, MAVROS uses this same technique if you give it the serial port directly:
https://github.com/mavlink/mavros/blob/7c8b06ba17c9912628cd7c64f1f238e989863418/libmavconn/src/serial.cpp#L100

**Comment by catch-twenty-two** [comment]
Tested it with the pocket beagle serial port which doesn't have a USB->Serial connection works fine, also tested with my FDTI adaptor.

**Pull request merged**
